"""The COACH indicator — a live discipline coach in Pine, generated from the
SPX playbook scaffold with its GEX + pivot levels BAKED IN.

This is the "before the fact" counterpart to the after-the-fact journal review.
The journal analysis found the operator's leaks are mechanical and checkable —
front-running the tag (95×), wrong side of the level (44×), extended entries,
adding to losers (17×). Those are exactly the conditions Pine CAN watch live.

WHAT IT DOES (honestly bounded):
  • Draws the baked GEX/pivot levels as lines, tinted by kind (call wall / put
    wall / flip = red-ish resistance-above / green support-below; the flip is
    the regime line).
  • Tracks SESSION VWAP (+σ bands), RSI, relative volume, ATR — live.
  • Emits a WAIT / ENTER / EXIT / WARN state each bar from a rule engine that
    encodes the playbook's discipline, NOT a price prediction:
      ENTER (green)  — price TAGGED a level and CLOSED back through it on the
                       correct side, with volume ≥ the session average. A clean,
                       confirmed reclaim/rejection at a real level.
      WAIT  (amber)  — price is NEAR a level but hasn't tagged/closed through it
                       (FRONT-RUN guard — a nudge to wait for the tag, not a
                       block: the backtest showed hard-blocking front-runs also
                       killed winners), or volume/VWAP don't confirm yet.
      WARN  (red)    — an unambiguous leak: wrong side of a wall, an extended
                       chase (far from VWAP + stretched RSI), or a knife into a
                       level. On 2026-07-15 these caught the −$1,650 wrong-side
                       call and the extended-chase puts with no false positives.
      EXIT  (blue)   — in-trade prompt: price reached the next level, or reverted
                       to VWAP after an extension — the "take it / it's done" cue.

WHAT IT CANNOT DO (same caveats as the GEX read): no live dealer-gamma feed —
the levels are last night's EOD estimate (which is exactly what framed a 0DTE
session); OI-based, blind to intraday 0DTE flow; not a buy/sell oracle. It flags
whether an entry breaks YOUR rules, not whether it will win.

Pure string assembly over the scaffold — no LLM, no I/O. Served as text by the
API for the UI to copy into TradingView (no .pine files, ADR-010).
"""
from __future__ import annotations

from . import reclaim_pine as _rp

#: Which baked level is a "wall" (hard resistance/support that a long should
#: not be bought ABOVE / a short sold BELOW) vs an ordinary shelf.
_WALL_KINDS = ("call wall", "put wall")
_FLIP_KINDS = ("flip", "gamma flip")


def _classify(label: str) -> str:
    """A baked level's role for the coach: 'callwall' | 'putwall' | 'flip' |
    'resistance' | 'support' | 'level'. Drives colour + the wrong-side rule."""
    l = (label or "").lower()
    if "call wall" in l:
        return "callwall"
    if "put wall" in l:
        return "putwall"
    if "flip" in l or "gamma" in l:
        return "flip"
    if "resist" in l:
        return "resistance"
    if "support" in l:
        return "support"
    return "level"


def build_coach_indicator(scaffold: dict) -> str | None:
    """Render the coach Pine for a playbook ``scaffold``. None when the scaffold
    carries no levels to bake (nothing to coach against)."""
    entries = _rp.gex_level_entries(scaffold)      # (price, label), high→low
    if not entries:
        return None

    reg = scaffold.get("regime") or {}
    session = str(scaffold.get("session") or "")
    gamma = str(reg.get("gamma") or "").lower()
    spot = reg.get("spot")

    # bake the levels as parallel Pine arrays: price, plain label, role
    prices, labels, roles = [], [], []
    for price, label in entries:
        prices.append(f"{float(price):.2f}")
        labels.append(_pine_str(_rp._clean_label(label)))
        roles.append(_pine_str(_classify(label)))
    px_arr = ", ".join(prices)
    lb_arr = ", ".join(labels)
    ro_arr = ", ".join(roles)

    # the flip (regime line) — the single most important level; find it if baked
    flip = next((float(p) for p, l in entries if _classify(l) == "flip"), None)
    flip_line = f"{flip:.2f}" if flip is not None else "na"

    header = (
        f"// SPX 0DTE COACH — generated by Vantage for the {session} session.\n"
        f"// Regime: {gamma} gamma"
        + (f", spot ~{float(spot):.0f}" if spot is not None else "")
        + f". {reg.get('vwap_regime') or ''}\n"
        "// A DISCIPLINE coach, not a signal oracle. It flags whether an entry\n"
        "// breaks your documented rules (front-run / wrong-side / extended /\n"
        "// knife) and confirms a CLEAN tag+reclaim on volume. Levels are the\n"
        "// nightly GEX/pivot estimate — 0DTE-blind, EOD-based. Not financial\n"
        "// advice. Add to an SPX (or SPY) chart, intraday timeframe.\n"
    )

    return header + _COACH_BODY.format(
        px_arr=px_arr, lb_arr=lb_arr, ro_arr=ro_arr,
        flip_line=flip_line, n_levels=len(prices),
    )


def _pine_str(s: str) -> str:
    """A double-quoted Pine string literal, quotes escaped."""
    return '"' + str(s or "").replace('"', "'") + '"'


# The coach body. Placeholders: {px_arr} {lb_arr} {ro_arr} {flip_line}
# {n_levels}. Written as a raw Pine v5 indicator; all the discipline logic lives
# here so the generator stays a pure level-baker.
_COACH_BODY = '''//@version=5
indicator("SPX 0DTE Coach", overlay=true, max_lines_count=200, max_labels_count=200)

// ── baked levels (from the nightly playbook) ─────────────────────────────────
var float[] lvlPx  = array.from({px_arr})
var string[] lvlLb = array.from({lb_arr})
var string[] lvlRo = array.from({ro_arr})
float flipLevel = {flip_line}

// ── inputs ───────────────────────────────────────────────────────────────────
tagTol   = input.float(0.05, "Tag tolerance (% of price)", minval=0.01, maxval=0.5, step=0.01, group="Coach", tooltip="How close counts as 'at' a level. 0.05% ~= 3.75pt at SPX 7500. Front-running = near but not within this AND not closed through.")
volLen   = input.int(20, "Rel-volume lookback (bars)", minval=5, group="Coach")
rsiLen   = input.int(14, "RSI length", minval=2, group="Coach")
extAtr   = input.float(2.0, "Extended = this many ATR from VWAP", minval=0.5, step=0.5, group="Coach", tooltip="Beyond this VWAP distance, a fresh entry is a CHASE (your 'don't buy an extension' leak).")
stallBars= input.int(10, "Stall window (bars)", minval=3, group="Coach", tooltip="How many bars of tight range = a coil. On 1m that's ~10 min of price stuck at a level.")
stallMax = input.float(3.0, "Stall = range under this many ATR", minval=0.5, step=0.5, group="Coach", tooltip="If the last N-bar range is under this many ATR, price is coiled. A 0DTE long bleeds theta while it waits for the break (validated: coiled entries -$178 avg vs +$177 non-stalled).")
showLines= input.bool(true, "Draw the baked levels", group="Display")
showVwap = input.bool(true, "Draw session VWAP + bands", group="Display")
showPanel= input.bool(true, "Show the coach panel (bottom-right)", group="Display")

// ── session VWAP + bands, RSI, relative volume, ATR ──────────────────────────
newSession = ta.change(time("D")) != 0
var float sumPV = na
var float sumV  = na
var float sumP2V= na
src = hlc3
if newSession or na(sumV)
    sumPV := src * volume
    sumV  := volume
    sumP2V:= src * src * volume
else
    sumPV += src * volume
    sumV  += volume
    sumP2V+= src * src * volume
vwap = sumV > 0 ? sumPV / sumV : na
variance = sumV > 0 ? math.max(sumP2V / sumV - vwap * vwap, 0) : 0
vsd = math.sqrt(variance)
vwUp = vwap + vsd
vwDn = vwap - vsd

rsi   = ta.rsi(close, rsiLen)
atr   = ta.atr(14)
avgV  = ta.sma(volume, volLen)
relV  = avgV > 0 ? volume / avgV : na
volOK = na(relV) ? false : relV >= 1.0          // participation >= session average

// ── nearest baked level to price, its role, and tag/side geometry ────────────
tol = close * tagTol / 100.0
var float nearPx = na
var string nearLb = na
var string nearRo = na
nearDist = 1e9
if array.size(lvlPx) > 0
    for i = 0 to array.size(lvlPx) - 1
        p = array.get(lvlPx, i)
        d = math.abs(close - p)
        if d < nearDist
            nearDist := d
            nearPx := p
            nearLb := array.get(lvlLb, i)
            nearRo := array.get(lvlRo, i)

atLevel   = not na(nearPx) and nearDist <= tol
nearLevel = not na(nearPx) and nearDist <= tol * 3 and not atLevel   // close, not tagged

// did THIS bar close back through the nearest level (a confirmed tag)?
crossedUp   = not na(nearPx) and low <= nearPx + tol and close > nearPx
crossedDown = not na(nearPx) and high >= nearPx - tol and close < nearPx

// regime side (positive-gamma range vs the flip): above flip = calmer/long-friendly
aboveFlip = na(flipLevel) or close >= flipLevel

// distance from VWAP in ATR — the "extended / chasing" gauge
vwGap = na(vwap) or na(atr) or atr == 0 ? na : (close - vwap) / atr
extendedUp   = not na(vwGap) and vwGap >=  extAtr
extendedDn   = not na(vwGap) and vwGap <= -extAtr

// ── STALL gauge: is price COILED (theta-bleed risk for a 0DTE long) ──────────
// The range over the last `stallBars` relative to ATR. A tight coil at a level
// means the break hasn't happened — a directional 0DTE just bleeds theta while
// it waits (validated: coiled entries netted -$178 avg vs +$177 non-stalled).
stallRange = ta.highest(high, stallBars) - ta.lowest(low, stallBars)
stallRatio = na(atr) or atr == 0 ? na : stallRange / atr
coiled = not na(stallRatio) and stallRatio <= stallMax
// how long has it been coiled (consecutive coiled bars) — longer = more bleed
var int coilBars = 0
coilBars := coiled ? coilBars + 1 : 0
// midday (ET) is when coils cluster — nudge the warning harder there
nyHour = hour(time, "America/New_York")
nyMin  = minute(time, "America/New_York")
mins   = nyHour * 60 + nyMin
midday = mins >= 11*60+30 and mins < 14*60
// theta warning: coiled AT/near a level, worse in midday. Only meaningful for a
// 0DTE LONG (you're paying theta to wait) — but shown for context on any bar.
stalledAtLevel = coiled and (atLevel or nearLevel) and coilBars >= stallBars

// ── the DISCIPLINE rules (your documented leaks) ─────────────────────────────
// WRONG SIDE: long above a call wall / durable resistance, short below a put
// wall / durable support. The wall should REPEL, not be chased through.
wrongSideLong  = atLevel and (nearRo == "callwall" or nearRo == "resistance") and close > nearPx
wrongSideShort = atLevel and (nearRo == "putwall"  or nearRo == "support")    and close < nearPx

// FRONT-RUN: near a level but not tagged and not closed through — the #1 leak.
frontRun = nearLevel and not crossedUp and not crossedDown

// EXTENDED: a fresh entry far from VWAP with a stretched RSI = a chase.
chaseLong  = extendedUp  and rsi >= 68
chaseShort = extendedDn  and rsi <= 32

// KNIFE (adding-to-loser proxy): price sliding DOWN into a support with
// below-average volume and below VWAP — catching a falling knife.
knife = atLevel and (nearRo == "support" or nearRo == "putwall") and close < vwap and not volOK and close < close[1]

// CLEAN ENTER: a confirmed tag+reclaim on the CORRECT side, with volume.
// Long: closed back UP through a support/flip while above VWAP-ish. Short: the
// mirror at a resistance/wall.
cleanLong  = crossedUp   and (nearRo == "support" or nearRo == "putwall" or nearRo == "flip") and volOK and not chaseLong
cleanShort = crossedDown and (nearRo == "resistance" or nearRo == "callwall") and volOK and not chaseShort

// EXIT prompt: in a move, price reached the NEXT opposing level, or reverted to
// VWAP after being extended (the "take it / it's done" cue). Level-agnostic
// (the coach can't see your fills) — it flashes when the tape says manage.
revertToVwap = (extendedUp[1] and close <= vwap) or (extendedDn[1] and close >= vwap)
reachedLevel = atLevel and (crossedUp or crossedDown)
exitCue = revertToVwap

// ── position tracking (from the coach's OWN last ENTER — Pine can't see your
// fills, so it follows the last clean signal it gave). This powers HOLD: when
// you're in a coached trade and it's RED, HOLD says 'underwater but still in
// plan — don't panic-sell', UNTIL it hits a stop-ish break or a real EXIT.
var int   posDir  = 0        // +1 long, -1 short, 0 flat
var float posEntry= na
var float posStop = na       // the level the trade was FROM — a close through it kills the thesis
if cleanLong
    posDir := 1
    posEntry := close
    posStop := nearPx - tol        // below the reclaimed level
if cleanShort
    posDir := -1
    posEntry := close
    posStop := nearPx + tol        // above the rejected level
// the thesis is dead if price closes back through the from-level → flat
if posDir == 1 and not na(posStop) and close < posStop
    posDir := 0
if posDir == -1 and not na(posStop) and close > posStop
    posDir := 0

inTrade = posDir != 0
pnlPts  = not inTrade or na(posEntry) ? na : (close - posEntry) * posDir
red     = inTrade and not na(pnlPts) and pnlPts < 0     // underwater

// HOLD: in a coached trade, underwater, but the from-level still holds (no
// stop break) and no EXIT/WARN — sit on your hands, don't fold a plan trade.
hold = red and not exitCue

// ── resolve ONE coach state (priority: WARN > EXIT > ENTER > HOLD > WAIT) ─────
// WARN is reserved for the leaks that were UNAMBIGUOUSLY bad in the backtest
// (wrong-side, extended-chase, knife — heeding these would have saved ~$3.6k on
// 2026-07-15). Front-running is a WAIT, not a WARN: the same backtest showed a
// hard front-run block also killed real winners (anticipatory fades that
// worked), so it's a nudge to wait for the tag, not a stop sign.
warn = wrongSideLong or wrongSideShort or chaseLong or chaseShort or knife
enter = cleanLong or cleanShort
// THETA: price is COILED at/near a level and hasn't broken — a 0DTE long bleeds
// premium while it waits. Advisory: it must not mask a real WARN/EXIT/ENTER (a
// break IS resolving), but it ranks above HOLD/WAIT because a quiet coil is
// exactly when theta erodes you unnoticed. Worse in midday, when coils cluster.
theta = stalledAtLevel and not warn and not exitCue and not enter
// front-run downgrades WAIT to an explicit "wait for the tag" (still amber)
state = warn ? "WARN" : exitCue ? "EXIT" : enter ? "ENTER" : theta ? "THETA" : hold ? "HOLD" : "WAIT"

// ── the ACTION verb — the ONE thing to read. Plain English, no jargon. ────────
// This answers "what do I do RIGHT NOW". Everything else in the panel explains it.
action = cleanLong      ? "BUY CALLS" :
         cleanShort     ? "BUY PUTS" :
         exitCue        ? "TAKE PROFIT" :
         (wrongSideLong or wrongSideShort) ? "WRONG SIDE — DON'T" :
         (chaseLong or chaseShort)         ? "DON'T CHASE" :
         knife          ? "DON'T CATCH IT" :
         theta          ? "STALLING — THETA RISK" :
         hold           ? "HOLD YOUR TRADE" :
         frontRun       ? "WAIT FOR THE TAG" :
                          "STAND ASIDE"

// the reason string — one plain sentence explaining the action
reason = wrongSideLong  ? "long above " + nearLb + " — the wall repels, don't buy through it" :
         wrongSideShort ? "short below " + nearLb + " — support repels, don't sell through it" :
         chaseLong      ? "price is " + str.tostring(vwGap, "#.#") + " ATR over VWAP — too extended to buy" :
         chaseShort     ? "price is " + str.tostring(math.abs(vwGap), "#.#") + " ATR under VWAP — too extended to sell" :
         knife          ? "falling into " + nearLb + " on thin volume — no bounce yet" :
         frontRun       ? "near " + nearLb + " but not tagged — wait for the close through it" :
         cleanLong      ? "reclaimed " + nearLb + " on volume — longs are confirmed here" :
         cleanShort     ? "rejected " + nearLb + " on volume — shorts are confirmed here" :
         exitCue        ? "snapped back to VWAP — the move is done, bank it" :
         theta          ? "coiled at " + nearLb + " for " + str.tostring(coilBars) + " bars — a 0DTE long bleeds theta while it decides" + (midday ? " (midday, watch it)" : "") :
         hold           ? str.tostring(pnlPts, "#.#") + "pt red but " + nearLb + " still holds — don't fold a plan trade" :
         atLevel        ? "at " + nearLb + " — wait for a confirmed close through it" :
                          "no level in range — nothing to do yet"

// ── the NARRATIVE — a plain-English read of the tape, shown ALWAYS (even in ───
// WAIT), so the panel tells a story instead of just flashing a stuck word. ────
regimeTxt = na(vwap) ? "" :
     (close >= vwap ? "Price is above VWAP" : "Price is below VWAP") +
     (aboveFlip ? " and above the flip — buyers favored. " : " and under the flip — sellers favored. ")
locTxt = na(nearPx) ? "No level nearby." :
     "Nearest is " + nearLb + " at " + str.tostring(nearPx, "#.#") +
     ", " + str.tostring(nearDist, "#.#") + "pt " + (close >= nearPx ? "below" : "above") + "."
narrative = regimeTxt + locTxt

// ── plots ─────────────────────────────────────────────────────────────────────
// session VWAP + bands
plot(showVwap ? vwap : na, "VWAP", color=color.new(#2f6df6, 0), linewidth=2)
plot(showVwap ? vwUp : na, "VWAP +σ", color=color.new(#2f6df6, 70), style=plot.style_line)
plot(showVwap ? vwDn : na, "VWAP -σ", color=color.new(#2f6df6, 70), style=plot.style_line)

// baked level lines (drawn once, on the first bar) with a right-hand label
if barstate.isfirst and showLines and array.size(lvlPx) > 0
    for i = 0 to array.size(lvlPx) - 1
        p  = array.get(lvlPx, i)
        ro = array.get(lvlRo, i)
        col = ro == "callwall" or ro == "resistance" ? color.new(#cf3b47, 30) : ro == "putwall" or ro == "support" ? color.new(#16915b, 30) : color.new(#b26a00, 20)
        line.new(bar_index, p, bar_index + 500, p, xloc=xloc.bar_index, extend=extend.right, color=col, width=ro == "callwall" or ro == "putwall" or ro == "flip" ? 2 : 1)
        label.new(bar_index + 500, p, array.get(lvlLb, i) + "  " + str.tostring(p, "#.#"), xloc=xloc.bar_index, style=label.style_label_left, textcolor=col, color=color.new(color.black, 100), size=size.small)

// background tint by state
bgcolor(state == "WARN" ? color.new(#cf3b47, 88) : state == "ENTER" ? color.new(#16915b, 88) : state == "EXIT" ? color.new(#2f6df6, 90) : state == "THETA" ? color.new(#e0a020, 88) : state == "HOLD" ? color.new(#9b6dff, 90) : na)

// a marker at the moment a state fires (not every bar)
stateChanged = state != state[1]
plotshape(stateChanged and state == "ENTER", title="ENTER", location=location.belowbar, style=shape.triangleup,   color=color.new(#16915b,0), size=size.small, text="ENTER")
plotshape(stateChanged and state == "WARN",  title="WARN",  location=location.abovebar, style=shape.xcross,       color=color.new(#cf3b47,0), size=size.tiny,  text="WARN")
plotshape(stateChanged and state == "EXIT",  title="EXIT",  location=location.abovebar, style=shape.diamond,      color=color.new(#2f6df6,0), size=size.tiny,  text="EXIT")
plotshape(stateChanged and state == "THETA", title="THETA", location=location.abovebar, style=shape.flag,         color=color.new(#e0a020,0), size=size.tiny,  text="θ decay")
plotshape(stateChanged and state == "HOLD",  title="HOLD",  location=location.belowbar, style=shape.square,       color=color.new(#9b6dff,0), size=size.tiny,  text="HOLD")

// ── your position, in plain words (always shown) ─────────────────────────────
posTxt = not inTrade ? "Flat — no position" :
     (posDir == 1 ? "Long from " : "Short from ") + str.tostring(posEntry, "#.#") +
     " · " + str.tostring(pnlPts, "+#.#;-#.#") + "pt " + (na(pnlPts) ? "" : pnlPts >= 0 ? "🟢" : "🔴")

// compact one-line tape read (the gauges, for the curious — not required reading)
tapeTxt = (na(vwap) ? "VWAP —" : (na(vwGap) ? "at VWAP" : str.tostring(vwGap, "+#.#;-#.#") + " ATR vs VWAP")) +
     " · RSI " + str.tostring(rsi, "#") + (rsi >= 70 ? "↑" : rsi <= 30 ? "↓" : "") +
     " · vol " + (na(relV) ? "—" : str.tostring(relV, "#.#") + "x" + (volOK ? "✓" : "")) +
     (coiled ? " · COILED " + str.tostring(coilBars) + "b" : "")

// ── the coach panel (BOTTOM-RIGHT — clear of chart indicators top-left and the
// playbook's tables top-right/bottom-center). ACTION → why → position → story. ─
var table panel = table.new(position.bottom_right, 1, 6, border_width=1, frame_width=1, frame_color=color.new(color.gray, 50))
if showPanel and barstate.islast
    actCol = (enter or hold) ? #16915b : exitCue ? #2f6df6 : warn ? #cf3b47 : theta ? #e0a020 : #4a5160
    // ROW 0 — the ACTION, big and colored. The one thing to read.
    table.cell(panel, 0, 0, action, text_color=color.white, bgcolor=color.new(actCol, 0), text_size=size.large, text_halign=text.align_center)
    // ROW 1 — one-sentence why
    table.cell(panel, 0, 1, reason, text_color=color.new(#e8eaed, 0), bgcolor=color.new(#1b2029, 0), text_size=size.normal, text_halign=text.align_left)
    // ROW 2 — YOUR POSITION, in words, color by P&L
    table.cell(panel, 0, 2, posTxt, text_color=color.white, bgcolor=color.new(not inTrade ? #2a2f38 : pnlPts >= 0 ? #145c3a : #6e2530, 0), text_size=size.normal, text_halign=text.align_center)
    // ROW 3 — the narrative: what price is actually doing (always shown)
    table.cell(panel, 0, 3, narrative, text_color=color.new(#c7ccd4, 0), bgcolor=color.new(#1b2029, 0), text_size=size.small, text_halign=text.align_left)
    // ROW 4 — the tape read (gauges), muted
    table.cell(panel, 0, 4, tapeTxt, text_color=color.new(#8a93a3, 0), bgcolor=color.new(#13171e, 0), text_size=size.small, text_halign=text.align_left)
    // ROW 5 — footer / legend
    table.cell(panel, 0, 5, "0DTE Coach · not advice · EOD levels", text_color=color.new(#5a6270, 0), bgcolor=color.new(#13171e, 0), text_size=size.tiny, text_halign=text.align_center)

// ── alerts (so the coach can flash even when you're not watching) ─────────────
alertcondition(stateChanged and state == "ENTER", "Coach: BUY", "Clean tag+reclaim on volume — take the entry")
alertcondition(stateChanged and state == "WARN",  "Coach: DON'T", "Rule break — wrong-side / chasing / knife")
alertcondition(stateChanged and state == "EXIT",  "Coach: TAKE PROFIT", "Reverted to VWAP — bank the trade")
alertcondition(stateChanged and state == "THETA", "Coach: THETA", "Coiled at a level — theta bleed on 0DTE longs")
alertcondition(stateChanged and state == "HOLD",  "Coach: HOLD",  "Red but the level holds — hold the plan")
'''
