"""The COACH indicator — a live discipline coach in Pine, generated from the
SPX playbook scaffold with its GEX + pivot levels BAKED IN.

This is the "before the fact" counterpart to the after-the-fact journal review.
The journal analysis found the operator's leaks are mechanical and checkable —
front-running the tag (95×), wrong side of the level (44×), extended entries,
adding to losers (17×). Those are exactly the conditions Pine CAN watch live.

WHAT IT DOES (honestly bounded):
  • Draws the baked GEX/pivot levels as lines, tinted by kind (call wall / put
    wall / flip = red-ish resistance-above / green support-below; the flip is
    the regime line).
  • Tracks SESSION VWAP (+σ bands), RSI, relative volume, ATR — live.
  • Emits a WAIT / ENTER / EXIT / WARN state each bar from a rule engine that
    encodes the playbook's discipline, NOT a price prediction:
      ENTER (green)  — price TAGGED a level and CLOSED back through it on the
                       correct side, with volume ≥ the session average. A clean,
                       confirmed reclaim/rejection at a real level.
      WAIT  (amber)  — price is NEAR a level but hasn't tagged/closed through it
                       (FRONT-RUN guard — a nudge to wait for the tag, not a
                       block: the backtest showed hard-blocking front-runs also
                       killed winners), or volume/VWAP don't confirm yet.
      WARN  (red)    — an unambiguous leak: wrong side of a wall, an extended
                       chase (far from VWAP + stretched RSI), or a knife into a
                       level. On 2026-07-15 these caught the −$1,650 wrong-side
                       call and the extended-chase puts with no false positives.
      EXIT  (blue)   — in-trade prompt: price reached the next level, or reverted
                       to VWAP after an extension — the "take it / it's done" cue.

WHAT IT CANNOT DO (same caveats as the GEX read): no live dealer-gamma feed —
the levels are last night's EOD estimate (which is exactly what framed a 0DTE
session); OI-based, blind to intraday 0DTE flow; not a buy/sell oracle. It flags
whether an entry breaks YOUR rules, not whether it will win.

Pure string assembly over the scaffold — no LLM, no I/O. Served as text by the
API for the UI to copy into TradingView (no .pine files, ADR-010).
"""
from __future__ import annotations

from . import reclaim_pine as _rp

#: Which baked level is a "wall" (hard resistance/support that a long should
#: not be bought ABOVE / a short sold BELOW) vs an ordinary shelf.
_WALL_KINDS = ("call wall", "put wall")
_FLIP_KINDS = ("flip", "gamma flip")


def _classify(label: str) -> str:
    """A baked level's role for the coach: 'callwall' | 'putwall' | 'flip' |
    'resistance' | 'support' | 'level'. Drives colour + the wrong-side rule."""
    l = (label or "").lower()
    if "call wall" in l:
        return "callwall"
    if "put wall" in l:
        return "putwall"
    if "flip" in l or "gamma" in l:
        return "flip"
    if "resist" in l:
        return "resistance"
    if "support" in l:
        return "support"
    return "level"


def build_coach_indicator(scaffold: dict) -> str | None:
    """Render the coach Pine for a playbook ``scaffold``. None when the scaffold
    carries no levels to bake (nothing to coach against)."""
    entries = _rp.gex_level_entries(scaffold)      # (price, label), high→low
    if not entries:
        return None

    reg = scaffold.get("regime") or {}
    session = str(scaffold.get("session") or "")
    gamma = str(reg.get("gamma") or "").lower()
    spot = reg.get("spot")

    # bake the levels as parallel Pine arrays: price, plain label, role
    prices, labels, roles = [], [], []
    for price, label in entries:
        prices.append(f"{float(price):.2f}")
        labels.append(_pine_str(_rp._clean_label(label)))
        roles.append(_pine_str(_classify(label)))
    px_arr = ", ".join(prices)
    lb_arr = ", ".join(labels)
    ro_arr = ", ".join(roles)

    # the flip (regime line) — the single most important level; find it if baked
    flip = next((float(p) for p, l in entries if _classify(l) == "flip"), None)
    flip_line = f"{flip:.2f}" if flip is not None else "na"

    header = (
        f"// SPX 0DTE COACH — generated by Vantage for the {session} session.\n"
        f"// Regime: {gamma} gamma"
        + (f", spot ~{float(spot):.0f}" if spot is not None else "")
        + f". {reg.get('vwap_regime') or ''}\n"
        "// A DISCIPLINE coach, not a signal oracle. It flags whether an entry\n"
        "// breaks your documented rules (front-run / wrong-side / extended /\n"
        "// knife) and confirms a CLEAN tag+reclaim on volume. Levels are the\n"
        "// nightly GEX/pivot estimate — 0DTE-blind, EOD-based. Not financial\n"
        "// advice. Add to an SPX (or SPY) chart, intraday timeframe.\n"
    )

    return header + _COACH_BODY.format(
        px_arr=px_arr, lb_arr=lb_arr, ro_arr=ro_arr,
        flip_line=flip_line, n_levels=len(prices),
    )


def _pine_str(s: str) -> str:
    """A double-quoted Pine string literal, quotes escaped."""
    return '"' + str(s or "").replace('"', "'") + '"'


# The coach body. Placeholders: {px_arr} {lb_arr} {ro_arr} {flip_line}
# {n_levels}. Written as a raw Pine v5 indicator; all the discipline logic lives
# here so the generator stays a pure level-baker.
_COACH_BODY = '''//@version=5
indicator("SPX 0DTE Coach", overlay=true, max_lines_count=200, max_labels_count=200)

// ── baked levels (from the nightly playbook) ─────────────────────────────────
var float[] lvlPx  = array.from({px_arr})
var string[] lvlLb = array.from({lb_arr})
var string[] lvlRo = array.from({ro_arr})
flipLevel = {flip_line}

// ── inputs ───────────────────────────────────────────────────────────────────
tagTol   = input.float(0.05, "Tag tolerance (% of price)", minval=0.01, maxval=0.5, step=0.01, group="Coach", tooltip="How close counts as 'at' a level. 0.05% ~= 3.75pt at SPX 7500. Front-running = near but not within this AND not closed through.")
volLen   = input.int(20, "Rel-volume lookback (bars)", minval=5, group="Coach")
rsiLen   = input.int(14, "RSI length", minval=2, group="Coach")
extAtr   = input.float(2.0, "Extended = this many ATR from VWAP", minval=0.5, step=0.5, group="Coach", tooltip="Beyond this VWAP distance, a fresh entry is a CHASE (your 'don't buy an extension' leak).")
showLines= input.bool(true, "Draw the baked levels", group="Display")
showVwap = input.bool(true, "Draw session VWAP + bands", group="Display")
showPanel= input.bool(true, "Show the coach panel (top-right)", group="Display")

// ── session VWAP + bands, RSI, relative volume, ATR ──────────────────────────
newSession = ta.change(time("D")) != 0
var float sumPV = na
var float sumV  = na
var float sumP2V= na
src = hlc3
if newSession or na(sumV)
    sumPV := src * volume
    sumV  := volume
    sumP2V:= src * src * volume
else
    sumPV += src * volume
    sumV  += volume
    sumP2V+= src * src * volume
vwap = sumV > 0 ? sumPV / sumV : na
variance = sumV > 0 ? math.max(sumP2V / sumV - vwap * vwap, 0) : 0
vsd = math.sqrt(variance)
vwUp = vwap + vsd
vwDn = vwap - vsd

rsi   = ta.rsi(close, rsiLen)
atr   = ta.atr(14)
avgV  = ta.sma(volume, volLen)
relV  = avgV > 0 ? volume / avgV : na
volOK = na(relV) ? false : relV >= 1.0          // participation >= session average

// ── nearest baked level to price, its role, and tag/side geometry ────────────
tol = close * tagTol / 100.0
var float nearPx = na
var string nearLb = na
var string nearRo = na
nearDist = 1e9
if array.size(lvlPx) > 0
    for i = 0 to array.size(lvlPx) - 1
        p = array.get(lvlPx, i)
        d = math.abs(close - p)
        if d < nearDist
            nearDist := d
            nearPx := p
            nearLb := array.get(lvlLb, i)
            nearRo := array.get(lvlRo, i)

atLevel   = not na(nearPx) and nearDist <= tol
nearLevel = not na(nearPx) and nearDist <= tol * 3 and not atLevel   // close, not tagged

// did THIS bar close back through the nearest level (a confirmed tag)?
crossedUp   = not na(nearPx) and low <= nearPx + tol and close > nearPx
crossedDown = not na(nearPx) and high >= nearPx - tol and close < nearPx

// regime side (positive-gamma range vs the flip): above flip = calmer/long-friendly
aboveFlip = na(flipLevel) or close >= flipLevel

// distance from VWAP in ATR — the "extended / chasing" gauge
vwGap = na(vwap) or na(atr) or atr == 0 ? na : (close - vwap) / atr
extendedUp   = not na(vwGap) and vwGap >=  extAtr
extendedDn   = not na(vwGap) and vwGap <= -extAtr

// ── the DISCIPLINE rules (your documented leaks) ─────────────────────────────
// WRONG SIDE: long above a call wall / durable resistance, short below a put
// wall / durable support. The wall should REPEL, not be chased through.
wrongSideLong  = atLevel and (nearRo == "callwall" or nearRo == "resistance") and close > nearPx
wrongSideShort = atLevel and (nearRo == "putwall"  or nearRo == "support")    and close < nearPx

// FRONT-RUN: near a level but not tagged and not closed through — the #1 leak.
frontRun = nearLevel and not crossedUp and not crossedDown

// EXTENDED: a fresh entry far from VWAP with a stretched RSI = a chase.
chaseLong  = extendedUp  and rsi >= 68
chaseShort = extendedDn  and rsi <= 32

// KNIFE (adding-to-loser proxy): price sliding DOWN into a support with
// below-average volume and below VWAP — catching a falling knife.
knife = atLevel and (nearRo == "support" or nearRo == "putwall") and close < vwap and not volOK and close < close[1]

// CLEAN ENTER: a confirmed tag+reclaim on the CORRECT side, with volume.
// Long: closed back UP through a support/flip while above VWAP-ish. Short: the
// mirror at a resistance/wall.
cleanLong  = crossedUp   and (nearRo == "support" or nearRo == "putwall" or nearRo == "flip") and volOK and not chaseLong
cleanShort = crossedDown and (nearRo == "resistance" or nearRo == "callwall") and volOK and not chaseShort

// EXIT prompt: in a move, price reached the NEXT opposing level, or reverted to
// VWAP after being extended (the "take it / it's done" cue). Level-agnostic
// (the coach can't see your fills) — it flashes when the tape says manage.
revertToVwap = (extendedUp[1] and close <= vwap) or (extendedDn[1] and close >= vwap)
reachedLevel = atLevel and (crossedUp or crossedDown)
exitCue = revertToVwap

// ── position tracking (from the coach's OWN last ENTER — Pine can't see your
// fills, so it follows the last clean signal it gave). This powers HOLD: when
// you're in a coached trade and it's RED, HOLD says 'underwater but still in
// plan — don't panic-sell', UNTIL it hits a stop-ish break or a real EXIT.
var int   posDir  = 0        // +1 long, -1 short, 0 flat
var float posEntry= na
var float posStop = na       // the level the trade was FROM — a close through it kills the thesis
if cleanLong
    posDir := 1
    posEntry := close
    posStop := nearPx - tol        // below the reclaimed level
if cleanShort
    posDir := -1
    posEntry := close
    posStop := nearPx + tol        // above the rejected level
// the thesis is dead if price closes back through the from-level → flat
if posDir == 1 and not na(posStop) and close < posStop
    posDir := 0
if posDir == -1 and not na(posStop) and close > posStop
    posDir := 0

inTrade = posDir != 0
pnlPts  = not inTrade or na(posEntry) ? na : (close - posEntry) * posDir
red     = inTrade and not na(pnlPts) and pnlPts < 0     // underwater

// HOLD: in a coached trade, underwater, but the from-level still holds (no
// stop break) and no EXIT/WARN — sit on your hands, don't fold a plan trade.
hold = red and not exitCue

// ── resolve ONE coach state (priority: WARN > EXIT > ENTER > HOLD > WAIT) ─────
// WARN is reserved for the leaks that were UNAMBIGUOUSLY bad in the backtest
// (wrong-side, extended-chase, knife — heeding these would have saved ~$3.6k on
// 2026-07-15). Front-running is a WAIT, not a WARN: the same backtest showed a
// hard front-run block also killed real winners (anticipatory fades that
// worked), so it's a nudge to wait for the tag, not a stop sign.
warn = wrongSideLong or wrongSideShort or chaseLong or chaseShort or knife
enter = cleanLong or cleanShort
// front-run downgrades WAIT to an explicit "wait for the tag" (still amber)
state = warn ? "WARN" : exitCue ? "EXIT" : enter ? "ENTER" : hold ? "HOLD" : "WAIT"

// the reason string for the panel/label
reason = wrongSideLong  ? "wrong side: long above " + nearLb :
         wrongSideShort ? "wrong side: short below " + nearLb :
         chaseLong      ? "extended: chasing " + str.tostring(vwGap, "#.#") + " ATR over VWAP" :
         chaseShort     ? "extended: chasing " + str.tostring(math.abs(vwGap), "#.#") + " ATR under VWAP" :
         knife          ? "knife into " + nearLb + " (below VWAP, thin vol)" :
         frontRun       ? "front-run: near " + nearLb + ", wait for the tag" :
         cleanLong      ? "clean reclaim of " + nearLb + " on volume" :
         cleanShort     ? "clean rejection of " + nearLb + " on volume" :
         exitCue        ? "reverted to VWAP — manage/take it" :
         hold           ? "red " + str.tostring(pnlPts, "#.#") + "pt but " + nearLb + " holds — hold the plan, don't fold" :
         atLevel        ? "at " + nearLb + " — wait for confirmation" :
                          "no level in range — wait for a tag"

// ── plots ─────────────────────────────────────────────────────────────────────
// session VWAP + bands
plot(showVwap ? vwap : na, "VWAP", color=color.new(#2f6df6, 0), linewidth=2)
plot(showVwap ? vwUp : na, "VWAP +σ", color=color.new(#2f6df6, 70), style=plot.style_line)
plot(showVwap ? vwDn : na, "VWAP -σ", color=color.new(#2f6df6, 70), style=plot.style_line)

// baked level lines (drawn once, on the first bar) with a right-hand label
if barstate.isfirst and showLines and array.size(lvlPx) > 0
    for i = 0 to array.size(lvlPx) - 1
        p  = array.get(lvlPx, i)
        ro = array.get(lvlRo, i)
        col = ro == "callwall" or ro == "resistance" ? color.new(#cf3b47, 30) : ro == "putwall" or ro == "support" ? color.new(#16915b, 30) : color.new(#b26a00, 20)
        line.new(bar_index, p, bar_index + 500, p, xloc=xloc.bar_index, extend=extend.right, color=col, width=ro == "callwall" or ro == "putwall" or ro == "flip" ? 2 : 1)
        label.new(bar_index + 500, p, array.get(lvlLb, i) + "  " + str.tostring(p, "#.#"), xloc=xloc.bar_index, style=label.style_label_left, textcolor=col, color=color.new(color.black, 100), size=size.small)

// background tint by state
bgcolor(state == "WARN" ? color.new(#cf3b47, 88) : state == "ENTER" ? color.new(#16915b, 88) : state == "EXIT" ? color.new(#2f6df6, 90) : state == "HOLD" ? color.new(#9b6dff, 90) : na)

// a marker at the moment a state fires (not every bar)
stateChanged = state != state[1]
plotshape(stateChanged and state == "ENTER", title="ENTER", location=location.belowbar, style=shape.triangleup,   color=color.new(#16915b,0), size=size.small, text="ENTER")
plotshape(stateChanged and state == "WARN",  title="WARN",  location=location.abovebar, style=shape.xcross,       color=color.new(#cf3b47,0), size=size.tiny,  text="WARN")
plotshape(stateChanged and state == "EXIT",  title="EXIT",  location=location.abovebar, style=shape.diamond,      color=color.new(#2f6df6,0), size=size.tiny,  text="EXIT")
plotshape(stateChanged and state == "HOLD",  title="HOLD",  location=location.belowbar, style=shape.square,       color=color.new(#9b6dff,0), size=size.tiny,  text="HOLD")

// ── the coach panel (top-right) ──────────────────────────────────────────────
var table panel = table.new(position.top_right, 2, 8, border_width=1)
if showPanel and barstate.islast
    stCol = state == "WARN" ? #cf3b47 : state == "ENTER" ? #16915b : state == "EXIT" ? #2f6df6 : state == "HOLD" ? #9b6dff : #b26a00
    table.cell(panel, 0, 0, "COACH", text_color=color.white, bgcolor=color.new(#13171e,0), text_size=size.normal)
    table.cell(panel, 1, 0, state, text_color=color.white, bgcolor=color.new(stCol,0), text_size=size.normal)
    table.cell(panel, 0, 1, "why", text_color=color.gray, text_size=size.small)
    table.cell(panel, 1, 1, reason, text_color=color.new(#13171e,0), text_size=size.small)
    table.cell(panel, 0, 2, "nearest", text_color=color.gray, text_size=size.small)
    table.cell(panel, 1, 2, na(nearPx) ? "—" : nearLb + " " + str.tostring(nearPx, "#.#") + " (" + str.tostring(nearDist, "#.#") + " away)", text_color=color.new(#13171e,0), text_size=size.small)
    table.cell(panel, 0, 3, "VWAP", text_color=color.gray, text_size=size.small)
    table.cell(panel, 1, 3, na(vwap) ? "—" : str.tostring(vwap, "#.#") + " (" + (na(vwGap) ? "—" : str.tostring(vwGap, "+#.#;-#.#") + " ATR)"), text_color=color.new(#13171e,0), text_size=size.small)
    table.cell(panel, 0, 4, "RSI", text_color=color.gray, text_size=size.small)
    table.cell(panel, 1, 4, str.tostring(rsi, "#") + (rsi >= 70 ? " overbought" : rsi <= 30 ? " oversold" : ""), text_color=color.new(#13171e,0), text_size=size.small)
    table.cell(panel, 0, 5, "rel-vol", text_color=color.gray, text_size=size.small)
    table.cell(panel, 1, 5, na(relV) ? "—" : str.tostring(relV, "#.##") + "x" + (volOK ? " ✓" : " (thin)"), text_color=color.new(#13171e,0), text_size=size.small)
    table.cell(panel, 0, 6, "regime", text_color=color.gray, text_size=size.small)
    table.cell(panel, 1, 6, aboveFlip ? "above flip" : "below flip", text_color=color.new(#13171e,0), text_size=size.small)
    table.cell(panel, 0, 7, "position", text_color=color.gray, text_size=size.small)
    table.cell(panel, 1, 7, not inTrade ? "flat" : (posDir == 1 ? "long " : "short ") + str.tostring(posEntry, "#.#") + " · " + str.tostring(pnlPts, "+#.#;-#.#") + "pt", text_color=na(pnlPts) ? color.gray : pnlPts >= 0 ? #16915b : #cf3b47, text_size=size.small)

// ── alerts (so the coach can flash even when you're not watching) ─────────────
alertcondition(stateChanged and state == "ENTER", "Coach: ENTER", "Clean tag+reclaim on volume")
alertcondition(stateChanged and state == "WARN",  "Coach: WARN",  "Rule break — front-run / wrong-side / extended / knife")
alertcondition(stateChanged and state == "EXIT",  "Coach: EXIT",  "Reverted to VWAP — manage the trade")
alertcondition(stateChanged and state == "HOLD",  "Coach: HOLD",  "Red but the level holds — hold the plan")
'''
